version: "3.7"
services:
  base:
    image: isodev:base
    build:
      context: ./base
      dockerfile: ubuntu20.04.Dockerfile

  main:
    image: isodev:main
    build: .
    depends_on:
      - base
    hostname: main
    restart: unless-stopped
    ports:
      - "8022:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
